# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink: /blog/:year/:month/:day/:title

# Setup
title:            Fern Ritchie
tagline:          'A new theme'
description:      'Welcome to my new theme'
url:              http://fernritchie.github.io
baseurl:          /

author:
  name:           'Fern Ritchie'
  url:            https://twitter.com/fernritchie12

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fernritchie/fernritchie
